steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - rxdiet-project/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}
      - rxdiet-project

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}
      - --region
      - ${_REGION}
      - --allow-unauthenticated

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: rxdiet-service
  _REGION: us-central1
  _REPOSITORY: rxdiet-repository
  _IMAGE: rxdiet-image
