export const uiStyles = {
  page: {
    minHeight: '100vh',
    padding: '32px 20px',
    background: 'linear-gradient(180deg, #eef7ff 0%, #dfeeff 52%, #eff8ff 100%)',
    color: '#12324a',
    fontFamily: '"Segoe UI", "Helvetica Neue", Helvetica, Arial, sans-serif',
  },
  shell: {
    maxWidth: '1100px',
    margin: '0 auto',
  },
  hero: {
    marginBottom: '20px',
    padding: '24px',
    borderRadius: '20px',
    background: 'linear-gradient(135deg, rgba(255,255,255,0.92), rgba(214,235,255,0.88))',
    border: '1px solid #bfddf7',
    boxShadow: '0 18px 45px rgba(80, 132, 179, 0.12)',
  },
  heroHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '16px',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  heroTitle: {
    margin: '0 0 8px',
    fontSize: '32px',
    lineHeight: 1.1,
  },
  heroText: {
    margin: 0,
    maxWidth: '700px',
    color: '#436581',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(280px, 340px) minmax(280px, 1fr)',
    gap: '20px',
    alignItems: 'start',
  },
  leftColumn: {
    display: 'grid',
    gap: '20px',
  },
  panel: {
    background: 'rgba(255, 255, 255, 0.84)',
    border: '1px solid #c8e0f6',
    borderRadius: '18px',
    padding: '18px',
    boxShadow: '0 12px 30px rgba(107, 154, 198, 0.12)',
    backdropFilter: 'blur(8px)',
  },
  panelTitle: {
    margin: '0 0 14px',
    fontSize: '18px',
  },
  status: {
    margin: '12px 0 0',
    padding: '10px 12px',
    borderRadius: '12px',
    background: '#edf7ff',
    color: '#215577',
    border: '1px solid #cbe6fb',
    whiteSpace: 'pre-wrap',
  },
  error: {
    background: '#fff1f1',
    color: '#8b2e2e',
    border: '1px solid #f2c5c5',
  },
  success: {
    background: '#eefaf1',
    color: '#236341',
    border: '1px solid #c5e8cf',
  },
  infoChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 12px',
    borderRadius: '999px',
    border: '1px solid #cbe3f9',
    background: '#f5fbff',
    color: '#37617f',
    fontSize: '13px',
  },
  infoChipSuccess: {
    background: '#eefaf1',
    border: '1px solid #c5e8cf',
    color: '#236341',
  },
  infoChipError: {
    background: '#fff2f2',
    border: '1px solid #f0c8c8',
    color: '#8a3434',
  },
  formRow: {
    display: 'grid',
    gap: '10px',
    marginBottom: '12px',
  },
  label: {
    display: 'grid',
    gap: '6px',
    fontSize: '14px',
    color: '#35556f',
  },
  input: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '11px 12px',
    borderRadius: '12px',
    border: '1px solid #bad6ef',
    background: '#f8fcff',
    color: '#143b59',
  },
  buttonRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
  },
  button: {
    padding: '10px 14px',
    borderRadius: '12px',
    border: '1px solid #71addc',
    background: '#3d93d1',
    color: '#ffffff',
    cursor: 'pointer',
    fontWeight: 600,
  },
  secondaryButton: {
    background: '#f4fbff',
    color: '#25608a',
    border: '1px solid #b9daf3',
  },
  subtleButton: {
    background: '#ffffff',
    color: '#446983',
    border: '1px solid #d0e4f5',
  },
  disabledButton: {
    opacity: 0.55,
    cursor: 'not-allowed',
  },
  userBadge: {
    marginTop: '14px',
    padding: '12px',
    borderRadius: '14px',
    background: '#f2f9ff',
    border: '1px solid #d4e8f8',
  },
  muted: {
    color: '#61819b',
    margin: 0,
  },
  usersList: {
    display: 'grid',
    gap: '12px',
  },
  userItem: {
    padding: '14px',
    borderRadius: '14px',
    border: '1px solid #d1e6f8',
    background: '#f8fcff',
  },
  selectedUserItem: {
    border: '1px solid #78b7e6',
    background: '#edf7ff',
    boxShadow: 'inset 0 0 0 1px rgba(120, 183, 230, 0.15)',
  },
  userHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    alignItems: 'flex-start',
    marginBottom: '10px',
  },
  userName: {
    margin: '0 0 4px',
    fontSize: '16px',
  },
  mono: {
    margin: 0,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: '12px',
    color: '#67879f',
    wordBreak: 'break-all',
  },
  chatTop: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    alignItems: 'center',
    marginBottom: '14px',
  },
  messageList: {
    display: 'grid',
    gap: '10px',
    minHeight: '240px',
    maxHeight: '420px',
    overflowY: 'auto',
    paddingRight: '6px',
    marginBottom: '16px',
  },
  messageItem: {
    padding: '12px 14px',
    borderRadius: '14px',
    background: '#f7fbff',
    border: '1px solid #d4e8f8',
  },
  messageSender: {
    margin: '0 0 6px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: '12px',
    color: '#5f7f98',
  },
  messageText: {
    margin: 0,
    color: '#183d5a',
    wordBreak: 'break-word',
  },
  composer: {
    display: 'grid',
    gap: '10px',
  },
  textarea: {
    minHeight: '88px',
    resize: 'vertical',
    padding: '12px',
    borderRadius: '14px',
    border: '1px solid #bad6ef',
    background: '#fbfdff',
    color: '#143b59',
    fontFamily: 'inherit',
  },
  blockPill: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '2px 8px',
    borderRadius: '999px',
    fontSize: '11px',
    fontWeight: 600,
    background: '#fff2f2',
    color: '#8a3434',
    border: '1px solid #f0c8c8',
    marginTop: '6px',
  },
}
